#ifndef HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_EXPORT __attribute__((dllexport))
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_IMPORT __attribute__((dllimport))
#else
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_EXPORT __declspec(dllexport)
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_IMPORT __declspec(dllimport)
#endif
#ifdef HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_BUILDING_DLL
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_PUBLIC HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_EXPORT
#else
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_PUBLIC HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_IMPORT
#endif
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_PUBLIC_TYPE HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_PUBLIC
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_LOCAL
#else
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_EXPORT __attribute__((visibility("default")))
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_IMPORT
#if __GNUC__ >= 4
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_PUBLIC __attribute__((visibility("default")))
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_LOCAL __attribute__((visibility("hidden")))
#else
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_PUBLIC
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_LOCAL
#endif
#define HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE_PUBLIC_TYPE
#endif

#endif  // HARUTO_OMNI_DRIVE_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_
